services:
  backend:
    build: .
    restart: always
    # ports:
    #   - 3000:3000
    environment:
      - DEVELOPMENT=false
      - PORT=3000
      - DB_SYNCHRONIZE=false
      - JWT_SECRET=CHANGETHISTOYOUROWNSECRET
      - TIRE_HOST=host.docker.internal
      - TIRE_PORT=1433
      - TIRE_USERNAME=sa
      - TIRE_PASSWORD=Charlie 13
      - TIRE_DATABASE=tire
      - PROWATCH_HOST=host.docker.internal
      - PROWATCH_PORT=1433
      - PROWATCH_USERNAME=sa
      - PROWATCH_PASSWORD=Charlie 13
      - PROWATCH_DATABASE=pwnt
  nginx:
    build: ./tire
    volumes:
      - ./cert:/etc/nginx/ssl/ # adds cert folder into nginx
    restart: always
    ports:
      - 80:80
      - 443:443
