name: CI
on: push

jobs:
  test-backend-lts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - run: npm ci
      - run: npm test

  test-backend-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm test

  test-frontend-lts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - name: Install dependencies
        working-directory: ./tire
        run: npm install
      - name: Run tests
        working-directory: ./tire
        run: npm run test service

  test-frontend-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        working-directory: ./tire
        run: npm install
      - name: Run tests
        working-directory: ./tire
        run: npm run test service
